In [46]:
# load packages 
import pandas as pd
import numpy as np
import pickle
import matplotlib.pyplot as plt

import time
# import xgboost

In [27]:
# read in pickles 
pds = []

for i in range(36):
    filename = 'data/' + str(i) + '_subset_cv_res_v2.pickle'
    df_i = pd.read_pickle(filename)
    pds.append(df_i)

In [29]:
df = pd.concat(pds)

In [71]:
df.groupby('model').agg({'mean_cv_F1_score':'mean', 'std_cv_F1_score':'mean','val_f1':'mean'}).reset_index()

         model  mean_cv_F1_score  std_cv_F1_score    val_f1
0  elastic_net          0.794054         0.015826  0.131784
1      xgboost          0.904939         0.010184  0.280896

In [78]:
df.groupby(['resampling_method', 'neighbors']).agg({'mean_cv_F1_score':'mean', 
                                     'std_cv_F1_score':'mean', 
                                     'val_f1':'mean'})

                             mean_cv_F1_score  std_cv_F1_score    val_f1
resampling_method neighbors
both              3                  0.779796         0.018195  0.238795
                  5                  0.778040         0.018445  0.239488
                  7                  0.778288         0.018721  0.233720
smote             3                  0.898764         0.009930  0.214347
                  5                  0.898155         0.010363  0.214899
                  7                  0.897705         0.011029  0.213395

In [62]:
df.groupby('subset').agg({'mean_cv_F1_score':'mean', 
                          'std_cv_F1_score':'mean',
                          'val_f1':'mean'}).sort_values('mean_cv_F1_score', ascending=False)

        mean_cv_F1_score  std_cv_F1_score    val_f1
subset
24              0.880638         0.012231  0.321033
21              0.879333         0.012395  0.275307
25              0.878720         0.013103  0.301824
26              0.878631         0.012373  0.280465
23              0.878577         0.012213  0.278640
22              0.877173         0.012077  0.288639
15              0.872696         0.010177  0.259548
12              0.870943         0.011721  0.216748
13              0.870911         0.011509  0.231389
17              0.870015         0.010350  0.234535
16              0.869738         0.010824  0.238072
14              0.868442         0.011050  0.229673
18              0.867589         0.014339  0.247144
19              0.865118         0.014795  0.226906
9               0.859444         0.013486  0.206194
20              0.859238         0.014099  0.235400
10              0.857183         0.014345  0.201653
11              0.855026         0.014275  0.187752
7               0.844482         0.015373  0.210575
6               0.843829         0.012700  0.189327
3               0.843043         0.012653  0.178270
8               0.841869         0.015702  0.196413
5               0.839952         0.014512  0.158800
4               0.838967         0.015996  0.182473
2               0.830026         0.015350  0.132745
0               0.829822         0.014334  0.187781
1               0.829644         0.013931  0.141787
34              0.827574         0.013501  0.155547
33              0.826197         0.011776  0.177978
35              0.825145         0.010844  0.193300
30              0.823753         0.012678  0.160880
31              0.822820         0.012410  0.140282
32              0.822122         0.011302  0.152671
29              0.811930         0.014408  0.118294
28              0.810682         0.011980  0.131954
27              0.810610         0.013364  0.158250

In [66]:
df.groupby('neighbors').agg({'mean_cv_F1_score':'mean', 
                          'std_cv_F1_score':'mean',
                          'val_f1':'mean'}).sort_values('mean_cv_F1_score', ascending=False)

           mean_cv_F1_score  std_cv_F1_score    val_f1
neighbors
3                  0.839280         0.014063  0.226571
5                  0.838098         0.014404  0.227193
7                  0.837996         0.014875  0.223558

In [8]:
# # read in results 
# df = pd.read_csv('cv_res.csv')

# # find best model 
# df.groupby('model').agg({'mean_cv_F1_score':'mean',
#                         'std_cv_F1_score':'mean'})

# # find best resampling method 
# df.groupby('resampling_method').agg({'mean_cv_F1_score':'mean',
#                                     'std_cv_F1_score':'mean'})

# # subset 
# df.groupby('subset').agg({'mean_cv_F1_score':'mean',
#                          'std_cv_F1_score':'mean'}).reset_index().sort_values('mean_cv_F1_score', ascending = False)

In [76]:
df.sort_values('mean_cv_F1_score', ascending=False)

,subset,model,resampling_method,neighbors,params,mean_cv_F1_score,std_cv_F1_score,val_f1
0,23,xgboost,none,None,"{'classifier': XGBClassifier(base_score=None, ...",0.928368,0.006765,0.333333
0,5,xgboost,none,None,"{'classifier': XGBClassifier(base_score=None, ...",0.926192,0.010879,0.181818
0,3,xgboost,smote,7,"{'classifier': XGBClassifier(base_score=None, ...",0.92587,0.01091,0.30303
0,7,xgboost,none,None,"{'classifier': XGBClassifier(base_score=None, ...",0.925463,0.007912,0.181818
0,3,xgboost,none,None,"{'classifier': XGBClassifier(base_score=None, ...",0.925359,0.006086,0.111111
...,...,...,...,...,...,...,...,...
0,28,elastic_net,both,5,"{'classifier': LogisticRegression(C=0.1, l1_ra...",0.473589,0.036054,0.132653
0,29,elastic_net,both,5,{'classifier': LogisticRegression(C=0.30000000...,0.473017,0.034983,0.133333
0,27,elastic_net,both,5,{'classifier': LogisticRegression(C=0.70000000...,0.472453,0.034305,0.132653
0,28,elastic_net,both,3,"{'classifier': LogisticRegression(C=0.1, l1_ra...",0.472371,0.036109,0.131313
0,27,elastic_net,both,3,{'classifier': LogisticRegression(C=0.70000000...,0.472316,0.037275,0.131313

### FOR LATER

In [64]:
# xgboost, both resampling, 24 subsets

X_train_24 = X_train[subsets[24]]

NameError: name 'X_train' is not defined

In [ ]:
both_xg_pipe = imbPipeline([
    ('over', SMOTE(sampling_strategy = 0.55)), 
    ('under', RandomUnderSampler()),
    ('classifier', XGBClassifier()) 
])

In [ ]:
xg_param_grid_fin = [
    {'classifier' : [XGBClassifier()],
    'classifier__n_estimators' : list(range(25,250,50)),
     'classifier__max_depth' : list(range(1,4)),
     'classifier__eta' : list(np.arange(0.1,0.5,0.2))
    }]

bothe_xg_gscv = GridSearchCV(both_xg_pipe, param_grid = xg_param_grid_fin, 
          cv = folds, verbose=0, scoring="f1_weighted")

In [ ]:
with io.capture_output() as captured:
    both_xg_gscv_24 = GridSearchCV(both_xg_pipe, param_grid = xg_param_grid_fin, 
          cv = folds, verbose=0, scoring="f1_weighted")
    both_xg_gscv_24.fit(X_train_24, y_train)

res24_both = pd.DataFrame(both_xg_gscv_24.cv_results_)